language: node_js
node_js:
  - 8
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
install:
  - npm install
script:
  - npm run test
  - npm run build
after_success:
  - ./node_modules/.bin/travis-deploy-once "npm run semantic-release"
